Repository andela/team-odd-bn-frontend, pull requests merged in 2020-02, with the labels that each got.

#40 #169258605 User can like and dislike
  package-lock.json
  src/__mocks__/accommodation/likeAndDislike.js
  src/__mocks__/accommodation/viewAccommodation.js
  src/__tests__/ImproveTest.js
  src/__tests__/actions/accommodation/likeAndDislikeTest.js
  src/__tests__/containers/accommodation/viewAccommodation.test.js
  src/__tests__/reducers/accommodation/likeAndDislikeReducer.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/components/GetStatsNav.js
  src/containers/accommodation/ViewAccommodations.js
  src/containers/admin/allUsers.js
  src/redux/actionTypes/accommodationActionTypes.js
  src/redux/actions/allAccommodation.js
  src/redux/actions/likeAndDislikeAction.js
  src/redux/reducers/accommodation/index.js
  src/redux/reducers/accommodation/likeAndDislikeReducer.js
  src/redux/reducers/index.js
  src/views/accommodation/ViewAccomodation.js
Labels: Work in progress, ready for review

#44 #171019468 User should be able to view specific booking
  src/App.js
  src/__mocks__/booking/booking.js
  src/__mocks__/fileMock.js
  src/__tests__/actions/booking/getSpecificBooking.test.js
  src/__tests__/containers/booking/viewAllBookings.test.js
  src/__tests__/containers/booking/viewSingleBooking.test.js
  src/__tests__/reducers/booking/viewSpecificBooking.test.js
  src/assets/css/App.scss
  src/assets/css/modal.scss
  src/containers/admin/allUsers.js
  src/containers/booking/viewAllBookings.js
  src/containers/booking/viewSingleBooking.js
  src/redux/actionTypes/bookingActionTypes.js
  src/redux/actions/bookings/viewSingleBookingActions.js
  src/redux/reducers/bookings/index.js
  src/redux/reducers/bookings/viewSingleBooking.js
  src/views/booking/viewSingleBooking.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/SearchTripStats.js
Labels: ready for review

#41 #169258604 a user should be able to book an accommodation facility
  src/App.js
  src/__mocks__/accommodation/viewAccommodation.js
  src/__mocks__/trips/requests.js
  src/__tests__/actions/bookings/bookAccommodationActions.js
  src/__tests__/containers/accommodation/viewAccommodation.test.js
  src/__tests__/containers/bookings/__snapshots__/bookAccommodation.test.js.snap
  src/__tests__/containers/bookings/bookAccommodation.test.js
  src/__tests__/reducers/bookings/bookAccommodation.test.js
  src/__tests__/reducers/popUp.test.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/assets/css/table.scss
  src/constants/bookings.js
  src/containers/accommodation/ViewAccommodations.js
  src/containers/admin/allUsers.js
  src/redux/actionTypes/bookingActionTypes.js
  src/redux/actions/PaginateAction.js
  src/redux/actions/bookings/bookAnAccommodation.js
  src/redux/reducers/bookings/bookAccommodationReducer.js
  src/redux/reducers/bookings/index.js
  src/redux/reducers/index.js
  src/redux/store/initialState.js
  src/views/accommodation/BookAccommodation.js
  src/views/accommodation/ViewAccomodation.js
Labels: ready for review

#42 #169258581 Implement notification feature
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/fileMock.js
  src/__mocks__/trips/requests.js
  src/__tests__/actionTests/getAllNotificationsActionTest.js
  src/__tests__/actionTests/markAllAsReadActionsTest.js
  src/__tests__/actionTests/markOneAsReadActionTests.js
  src/__tests__/containers/Notifications.test.js
  src/__tests__/containers/__snapshots__/Notifications.test.js.snap
  src/__tests__/reducerTests/getAllNotificationsReducerTest.js
  src/__tests__/reducerTests/markAllAsReducerTest.js
  src/__tests__/reducerTests/markOneAsReducerTests.js
  src/__tests__/sidebar.js
  src/assets/css/notification.scss
  src/assets/css/sidenav/sidebar.scss
  src/assets/css/table.scss
  src/components/Profile.js
  src/constants/trips.js
  src/containers/TripsContainer/oneway.js
  src/containers/notifications/Notifications.js
  src/helpers/notificationHelper.js
  src/redux/actionTypes/notificationActionTypes.js
  src/redux/actions/notifications/getAllNotificationActions.js
  src/redux/actions/notifications/markAllAsReadActions.js
  src/redux/actions/notifications/markOneAsReadActions.js
  src/redux/reducers/index.js
  src/redux/reducers/notificationsReducers/getAllNotificationsReducer.js
  src/redux/reducers/notificationsReducers/index.js
  src/redux/reducers/notificationsReducers/markAllAsReadReducer.js
  src/redux/reducers/notificationsReducers/markOneAsReadReducer.js
  src/redux/store/initialState.js
  src/views/Dashboard.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/Dashboard/sidebar/TopRightSide.js
  src/views/trips/RequestsView.js
  src/views/trips/oneWayView.js
Labels: ready for review

#45 #171019461 user can get all bookings under him or her
  src/App.js
  src/__mocks__/booking/booking.js
  src/__tests__/components/modal.test.js
  src/__tests__/containers/accommodation/viewAccommodation.test.js
  src/__tests__/containers/booking/__snapshots__/viewAllBookings.test.js.snap
  src/__tests__/containers/booking/__snapshots__/viewSingleBooking.test.js.snap
  src/__tests__/containers/booking/viewAllBookings.test.js
  src/__tests__/containers/booking/viewSingleBooking.test.js
  src/assets/css/base.scss
  src/assets/css/bookings/userBookings.scss
  src/assets/css/table.scss
  src/assets/images/ViewAllBookings/icon1.png
  src/assets/images/ViewAllBookings/icon2.png
  src/assets/images/ViewAllBookings/icon3.png
  src/assets/images/ViewAllBookings/icon4.png
  src/containers/accommodation/ViewAccommodations.js
  src/containers/bookings/ViewBookings.js
  src/containers/bookings/viewAllBookings.js
  src/containers/bookings/viewSingleBooking.js
  src/redux/actions/bookings/viewSingleBookingActions.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/accommodation/ViewAccomodation.js
Labels: Work in progress, ready for review

#48 #171180313 Improve existing trips and bookings design
  src/__mocks__/trips/multicity.js
  src/__tests__/containers/Trips/multicity.js
  src/__tests__/views/trips/OnewayTrip.test.js
  src/assets/css/accommodation/allAccommodation.scss
  src/assets/css/bookings/userBookings.scss
  src/assets/css/footer.scss
  src/assets/css/oneway.scss
  src/assets/css/roundtrip.scss
  src/assets/css/table.scss
  src/containers/Trips/MulticityTrip.js
  src/containers/TripsContainer/oneway.js
  src/containers/accommodation/ViewSpecificAccommodation.js
  src/containers/bookings/ViewBookings.js
  src/redux/actions/tripsActions/statsTripActions.js
Labels: done

#46 #171146588 Fix user search functionality
  package-lock.json
  package.json
  src/__mocks__/accommodation/viewAccommodation.js
  src/__mocks__/admin/admin.js
  src/__mocks__/booking/booking.js
  src/__mocks__/trips/requests.js
  src/__tests__/containers/accommodation/viewAccommodation.test.js
  src/__tests__/reducers/PaginationReducer.test.js
  src/__tests__/views/trips/CommonRequests.test.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/__tests__/views/trips/EditTrip.test.js
  src/assets/css/App.scss
  src/assets/css/accommodation/allAccommodation.scss
  src/assets/css/accommodation/viewSpeciAccommodation.scss
  src/assets/css/bookings/userBookings.scss
  src/assets/css/footer.scss
  src/assets/css/oneway.scss
  src/assets/css/roundtrip.scss
  src/assets/css/selectOption.scss
  src/assets/css/sidenav/sidebar.scss
  src/assets/css/sidenav/tooltip.scss
  src/assets/css/table.scss
  src/assets/images/next_icon.png
  src/assets/images/prev_icon.png
  src/components/Navbar.js
  src/components/Profile.js
  src/constants/trips.js
  src/containers/Trips/ApprovalTable.js
  src/containers/TripsContainer/Requests.js
  src/containers/accommodation/ViewAccommodations.js
  src/containers/accommodation/ViewSpecificAccommodation.js
  src/containers/admin/UserRoles.js
  src/containers/admin/allUsers.js
  src/containers/bookings/ViewBookings.js
  src/containers/notifications/Notifications.js
  src/containers/user/email/verifyEmail.js
  src/containers/user/signin/signin.js
  src/helpers/filter.js
  src/redux/actionTypes/searchActionTypes.js
  src/redux/actions/search/searchAction.js
  src/redux/actions/tripsActions/fetchRequests.js
  src/redux/reducers/searchReducers/searchReducers.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/TopLeftSide.js
  src/views/Dashboard/sidebar/TopRightSide.js
  src/views/accommodation/BookAccommodation.js
  src/views/accommodation/ViewAccomodation.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/EditTrip.js
  src/views/trips/ManagerView.js
  src/views/trips/RequestsView.js
Labels: ready for review

#50 #171195669 Optimize like and dislike functionality
  package-lock.json
  package.json
  src/__tests__/ImproveTest.js
  src/__tests__/actions/accommodation/viewAccommodations.js
  src/__tests__/reducers/accommodation/viewAccommodation.js
  src/assets/css/accommodation/allAccommodation.scss
  src/assets/css/bookings/userBookings.scss
  src/assets/css/table.scss
  src/containers/bookings/ViewBookings.js
  src/helpers/joinLikesAccomodation.js
  src/helpers/likeAndDislikeStyle.js
  src/redux/actions/likeAndDislikeAction.js
  src/redux/reducers/accommodation/viewAccomodationReducer.js
  src/views/Dashboard/sidebar/TopRightSide.js
  src/views/accommodation/ViewAccomodation.js
  src/views/bookings/viewSingleBooking.js
Labels: done

#51 Improve existing logical operation
  .env.example
  src/__mocks__/trips/multicity.js
  src/__tests__/actionTests/profileActionTests.js
  src/__tests__/actions/Trips/multicity.js
  src/__tests__/reducers/Trips/multicity.js
  src/assets/css/authentication.scss
  src/components/CreateProfile.js
  src/components/Profile.js
  src/components/index.js
  src/containers/Trips/MulticityTrip.js
  src/containers/TripsContainer/Requests.js
  src/containers/TripsContainer/SingleRequest.js
  src/containers/TripsContainer/oneway.js
  src/containers/trips/SearchStats.js
  src/containers/user/email/successfulVerification.js
  src/redux/actions/multicityActions.js
  src/redux/actions/profileActions.js
  src/redux/reducers/multicityReducer.js
  src/views/Dashboard/sidebar/index.js
Labels: ready for review
