Repository andela/team-odd-bn-frontend, pull requests merged in 2020-01, with the labels that each got.

#9 #169258574 Configure storybook
  .babelrc
  .circleci/config.yml
  .storybook/config.js
  package-lock.json
  package.json
  src/App.js
  src/__tests__/storyshots.test.js
  src/redux/actions/demoActions.js
  src/redux/reducers/demoReducers.js
  src/stories/index.stories.js
Labels: ready for review

#15 #169258578 User should login with Facebook and Google Account
  .babelrc
  .circleci/config.yml
  .eslintrc.json
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/fileMock.js
  src/__tests__/__snapshots__/dashboard.js.snap
  src/__tests__/__snapshots__/signin.test.js.snap
  src/__tests__/__snapshots__/signup.test.js.snap
  src/__tests__/dashboard.js
  src/__tests__/signin.test.js
  src/__tests__/signup.test.js
  src/__tests__/socialAuth.test.js
  src/assets/css/errors.scss
  src/assets/css/socialLogin.scss
  src/assets/css/style.css
  src/assets/css/style.scss
  src/assets/images/close_16px.png
  src/assets/images/facebook_24px.png
  src/assets/images/facebook_32px.png
  src/assets/images/facebook_64px.png
  src/assets/images/google_24px.png
  src/assets/images/google_32px.png
  src/assets/images/google_64px.png
  src/components/Demo.js
  src/components/socialLoginButton.js
  src/config/index.js
  src/containers/user/signin/Signin.js
  src/containers/user/social/SocialAuthLogin.js
  src/helpers/extractQueryInfo.js
  src/redux/actionTypes/demoActionTypes.js
  src/redux/actionTypes/socialAuthActionType.js
  src/redux/actions/demoActions.js
  src/redux/actions/socialAuthAction.js
  src/redux/reducers/demoReducers.js
  src/redux/reducers/index.js
  src/redux/reducers/socialAuthReducer.js
  src/redux/store/initialState.js
  src/testConfigurations/__mocks__/fileMock.js
  src/views/Dashboard/index.js
  src/views/social/Facebook.js
  src/views/social/Google.js
  webpack.config.babel.js
Labels: feedback implemented

#11 #169258575 A user should be able to signup
  .env.example
  .eslintrc.json
  html-report/report.html
  jest.config.js
  package.json
  src/App.js
  src/__mocks__/auth/authMock.js
  src/__mocks__/fileMock.js
  src/__tests__/AppTests.test.js
  src/__tests__/VerifyEmail.test.js
  src/__tests__/__snapshots__/AppTests.test.js.snap
  src/__tests__/__snapshots__/VerifyEmail.test.js.snap
  src/__tests__/__snapshots__/signup.test.js.snap
  src/__tests__/actions/auth/signup.test.js
  src/__tests__/components/InputField.test.js
  src/__tests__/components/Spinner.js
  src/__tests__/components/SubmitButton.js
  src/__tests__/components/__snapshots__/InputField.test.js.snap
  src/__tests__/components/__snapshots__/Spinner.js.snap
  src/__tests__/components/__snapshots__/SubmitButton.js.snap
  src/__tests__/reducers/auth/signup.test.js
  src/__tests__/signout.js
  src/__tests__/signup.test.js
  src/__tests__/socialAuth.test.js
  src/__tests__/views/auth/__snapshots__/signup.test.js.snap
  src/__tests__/views/auth/__snapshots__/signupView.test.js.snap
  src/__tests__/views/auth/signup.test.js
  src/__tests__/views/auth/signupView.test.js
  src/assets/css/App.scss
  src/assets/css/base.scss
  src/assets/css/signup.scss
  src/assets/css/socialLogin.scss
  src/assets/css/spinner.scss
  src/assets/images/icon-combined.png
  src/assets/images/index.js
  src/components/InputField.js
  src/components/Spinner.js
  src/components/SubmitButton.js
  src/components/socialLoginButton.js
  src/constants/index.js
  src/constants/signUp.js
  src/containers/user/signup/signup.js
  src/helpers/apiCall.js
  src/helpers/notificationPopUp.js
  src/redux/actionTypes/authActionTypes.js
  src/redux/actions/authActions.js
  src/redux/actions/index.js
  src/redux/reducers/authReducers/index.js
  src/redux/reducers/authReducers/signupReducers.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/redux/store/initialState.js
  src/views/auth/CommonAuthForm.js
  src/views/auth/SignupView.js
  src/views/auth/VerifyEmail.js
  src/views/social/Facebook.js
  src/views/social/Google.js
  webpack.config.babel.js
Labels: ready for review

#13 #169258577 User should be able to Login
  .eslintrc.json
  html-report/report.html
  jest.config.js
  package.json
  src/App.js
  src/__mocks__/__loginTestMock__/loginMock.js
  src/__tests__/__snapshots__/signin.test.js.snap
  src/__tests__/actions/auth/signin.test.js
  src/__tests__/components/InputField.test.js
  src/__tests__/components/__snapshots__/InputField.test.js.snap
  src/__tests__/reducers/auth/signin.test.js
  src/__tests__/signin.test.js
  src/__tests__/verifyToken.test.js
  src/__tests__/views/auth/__snapshots__/loginView.test.js.snap
  src/__tests__/views/auth/loginView.test.js
  src/assets/css/App.scss
  src/assets/css/base.scss
  src/assets/css/signin.scss
  src/assets/css/spinner.scss
  src/assets/images/icon.js
  src/components/InputField.js
  src/components/SubmitButton.js
  src/constants/login.js
  src/containers/user/signin/Signin.js
  src/containers/user/signin/signin.js
  src/helpers/generateToken.js
  src/helpers/notificationPopUp.js
  src/helpers/verifyToken.js
  src/redux/actionTypes/authActionTypes.js
  src/redux/actions/signinActions.js
  src/redux/reducers/authReducers/index.js
  src/redux/reducers/authReducers/signinReducer.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/redux/store/initialState.js
  src/views/auth/LoginView.js
  webpack.config.babel.js
Labels: feedback implemented, ready for review

#12 #169258576 User should be able to reset password
  html-report/report.html
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/auth/resetPasswordMock.js
  src/__tests__/__snapshots__/footer.js.snap
  src/__tests__/__snapshots__/header.js.snap
  src/__tests__/actions/resetPasswordActions.test.js
  src/__tests__/components/Spinner.test.js
  src/__tests__/components/SubmitButton.test.js
  src/__tests__/components/__snapshots__/Spinner.test.js.snap
  src/__tests__/components/__snapshots__/SubmitButton.test.js.snap
  src/__tests__/components/__snapshots__/inputBox.test.js.snap
  src/__tests__/components/inputBox.test.js
  src/__tests__/containers/forgotPassword.test.js
  src/__tests__/containers/resetPassword.test.js
  src/__tests__/footer.js
  src/__tests__/header.js
  src/__tests__/reducers/resetPasswordReducer.test.js
  src/__tests__/signout.js
  src/__tests__/signout.test.js
  src/__tests__/views/Dashboard.test.js
  src/__tests__/views/__snapshots__/Dashboard.test.js.snap
  src/__tests__/views/auth/__snapshots__/signup.test.js.snap
  src/__tests__/views/auth/signup.test.js
  src/__tests__/views/passwordResetView.test.js
  src/assets/css/App.scss
  src/assets/css/base.scss
  src/assets/css/footer.scss
  src/assets/css/header.scss
  src/assets/css/passwordReset.scss
  src/components/footer.js
  src/components/header.js
  src/constants/passwordReset.js
  src/containers/user/password/forgotPassword.js
  src/containers/user/password/resetPassword.js
  src/containers/user/signout/signout.js
  src/redux/actionTypes/authActionTypes.js
  src/redux/actions/resetPasswordActions.js
  src/redux/reducers/authReducers/index.js
  src/redux/reducers/authReducers/resetPasswordReducer.js
  src/views/Dashboard.js
  src/views/forgotPasswordView.js
  src/views/resetPasswordView.js
  webpack.config.babel.js
Labels: feedback implemented

#14 #169258579 User can be able to view and update profile
  .circleci/config.yml
  .env.example
  html-report/report.html
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__mocks__/fileMock.js
  src/__tests__/actionTests/getUsersActionTests.js
  src/__tests__/actionTests/profileActionTests.js
  src/__tests__/componentTests/__snapshots__/profileTests.js.snap
  src/__tests__/componentTests/__snapshots__/spinnerTests.js.snap
  src/__tests__/componentTests/inputTextTests.js
  src/__tests__/componentTests/navbarTests.js
  src/__tests__/componentTests/profileTests.js
  src/__tests__/componentTests/spinnerTests.js
  src/__tests__/reducerTests/profileReducerTests.js
  src/assets/css/App.scss
  src/assets/css/base.scss
  src/assets/css/navbar.css
  src/assets/css/profile.css
  src/assets/css/spinner.css
  src/assets/images/drop-down.png
  src/assets/images/logo.png
  src/assets/images/notifications.png
  src/assets/images/profile-picture.png
  src/assets/images/profile-picture1.png
  src/assets/images/profile-picture2.png
  src/assets/images/profile.png
  src/components/Navbar.js
  src/components/Profile.js
  src/components/common/TextInput.js
  src/components/index.js
  src/constants/passwordReset.js
  src/constants/signUp.js
  src/containers/user/password/resetPassword.js
  src/redux/actionTypes/profileActionTypes.js
  src/redux/actions/getAllUsersActions.js
  src/redux/actions/profileActions.js
  src/redux/actions/updateProfileActions.js
  src/redux/reducers/ProfileReducers.js
  src/redux/reducers/getAllUsersReducers.js
  src/redux/reducers/index.js
  src/redux/reducers/updateProfileReducer.js
  webpack.config.babel.js
Labels: feedback implemented

#17 #169258634 User should be able to signout
  .gitignore
  html-report/report.html
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/fileMock.js
  src/__tests__/__snapshots__/dashboard.js.snap
  src/__tests__/dashboard.js
  src/__tests__/signout.test.js
  src/config/index.js
  src/redux/actionTypes/signoutActionTypes.js
  src/redux/actions/signoutAction.js
  src/redux/reducers/index.js
  src/redux/reducers/signoutReducer.js
  src/views/Dashboard/index.js
Labels: ready for review

#19 #170602242 Design landing page
  html-report/report.html
  src/App.js
  src/__tests__/__snapshots__/landingPage.test.js.snap
  src/__tests__/landingPage.test.js
  src/assets/css/style.css
  src/assets/images/background.jpg
  src/assets/images/landing.png
  src/assets/images/responsive.png
  src/components/LandingPage.js
Labels: ready for review

#23 #170574394 user should be able to verify email address
  html-report/report.html
  src/App.js
  src/__mocks__/auth/verifyEmailMock.js
  src/__tests__/actions/verifyEmailActions.test.js
  src/__tests__/containers/successfulVerification.test.js
  src/__tests__/containers/verifyEmail.test.js
  src/__tests__/header.js
  src/__tests__/reducers/verifyEmailReducer.test.js
  src/__tests__/views/auth/passwordResetView.test.js
  src/__tests__/views/auth/signup.test.js
  src/__tests__/views/auth/verifyEmailView.test.js
  src/assets/css/authentication.scss
  src/assets/css/base.scss
  src/assets/css/header.scss
  src/assets/css/passwordReset.scss
  src/assets/images/default_user_16px.png
  src/assets/images/default_user_24px.png
  src/assets/images/default_user_32px.png
  src/assets/images/default_user_64.png
  src/assets/images/email_icon_50px.png
  src/assets/images/verified_account.png
  src/components/header.js
  src/constants/passwordReset.js
  src/constants/verifyEmail.js
  src/containers/user/email/successfulVerification.js
  src/containers/user/email/verifyEmail.js
  src/containers/user/password/forgotPassword.js
  src/containers/user/password/resetPassword.js
  src/containers/user/signup/signup.js
  src/redux/actionTypes/authActionTypes.js
  src/redux/actions/verifyEmailActions.js
  src/redux/reducers/authReducers/index.js
  src/redux/reducers/authReducers/verifyEmailReducer.js
  src/views/auth/LoginView.js
  src/views/auth/forgotPasswordView.js
  src/views/auth/resetPasswordView.js
  src/views/auth/verifyEmailView.js
Labels: ready for review

#25 #169258580 A user should be able to view requests and a single request.
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/trips/requests.js
  src/__tests__/__snapshots__/VerifyEmail.test.js.snap
  src/__tests__/actions/Trips/fetchRequests.test.js
  src/__tests__/components/Action.test.js
  src/__tests__/components/Status.test.js
  src/__tests__/components/SubmitButton.js
  src/__tests__/components/__snapshots__/Action.test.js.snap
  src/__tests__/components/__snapshots__/Status.test.js.snap
  src/__tests__/helpers/corasell.js
  src/__tests__/reducers/Trips/signup.test.js
  src/__tests__/views/trips/CommonRequests.test.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/__tests__/views/trips/CommonTable.test.js
  src/__tests__/views/trips/Requests.test.js
  src/__tests__/views/trips/RequestsView.test.js
  src/__tests__/views/trips/SingleRequests.test.js
  src/__tests__/views/trips/__snapshots__/CommonRequests.test.js.snap
  src/__tests__/views/trips/__snapshots__/CommonSingleRequest.test.js.snap
  src/__tests__/views/trips/__snapshots__/CommonTable.test.js.snap
  src/__tests__/views/trips/__snapshots__/Requests.test.js.snap
  src/__tests__/views/trips/__snapshots__/RequestsView.test.js.snap
  src/__tests__/views/trips/__snapshots__/SingleRequests.test.js.snap
  src/assets/css/base.scss
  src/assets/css/table.scss
  src/components/Action.js
  src/components/Navbar.js
  src/components/Profile.js
  src/components/Sidebar/SideDrawer/SideDrawer.js
  src/components/Status.js
  src/constants/trips.js
  src/containers/Trips/Requests.js
  src/containers/Trips/SingleRequest.js
  src/helpers/carousel.js
  src/redux/actionTypes/tripActionTypes.js
  src/redux/actions/tripsActions/fetchRequests.js
  src/redux/reducers/index.js
  src/redux/reducers/tripReducers/index.js
  src/redux/reducers/tripReducers/requestsReducers.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/RightSide.js
  src/views/Dashboard/sidebar/index.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/CommonTable.js
  src/views/trips/RequestsView.js
  src/views/trips/SingleRequestView.js
Labels: ready for review

#26 #170670073 User can be able to make a round trip request
  html-report/report.html
  src/App.js
  src/__mocks__/fileMock.js
  src/__tests__/actionTests/getAllCitiesActionTests.js
  src/__tests__/actionTests/roundTripActionTests.js
  src/__tests__/componentTests/__snapshots__/roundTripTests.js.snap
  src/__tests__/componentTests/__snapshots__/tripHeaderTest.js.snap
  src/__tests__/componentTests/__snapshots__/tripTypesTests.js.snap
  src/__tests__/componentTests/roundTripTests.js
  src/__tests__/componentTests/tripHeaderTest.js
  src/__tests__/componentTests/tripTypesTests.js
  src/__tests__/reducerTests/getAllCitiesReducerTests.js
  src/__tests__/reducerTests/roundTripReducerTests.js
  src/assets/css/App.scss
  src/assets/css/authentication.scss
  src/assets/css/base.scss
  src/assets/css/footer.scss
  src/assets/css/header.scss
  src/assets/css/navbar.css
  src/assets/css/profile.css
  src/assets/css/roundtrip.scss
  src/assets/css/sidenav/sidebar.scss
  src/assets/css/sidenav/tooltip.scss
  src/assets/css/style.css
  src/assets/css/style.scss
  src/assets/css/table.scss
  src/components/Navbar.js
  src/components/Profile.js
  src/components/footer.js
  src/components/trips/TripHeader.js
  src/components/trips/TripTypes.js
  src/containers/trips/RoundTrip.js
  src/containers/user/email/successfulVerification.js
  src/containers/user/email/verifyEmail.js
  src/containers/user/password/forgotPassword.js
  src/containers/user/password/resetPassword.js
  src/redux/actionTypes/tripsActionTypes.js
  src/redux/actions/getAllCitiesActions.js
  src/redux/actions/roundTripActions.js
  src/redux/reducers/getAllCitiesReducers.js
  src/redux/reducers/index.js
  src/redux/reducers/roundTripReducer.js
  src/redux/reducers/tripReducers/index.js
  src/views/Dashboard.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/Dashboard/sidebar/RightSide.js
  src/views/trips/CommonRequests.js
Labels: ready for review

#27 #169258599 Travel Admin can create accommodation facility
  html-report/report.html
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__mocks__/accommodation/createAccommodation.js
  src/__mocks__/fileMock.js
  src/__tests__/actions/accommodation/createAccommodation.test.js
  src/__tests__/actions/resetPasswordActions.test.js
  src/__tests__/components/modal.test.js
  src/__tests__/containers/accommodation/createAccommodation.test.js
  src/__tests__/helpers/isTravelAdmin.test.js
  src/__tests__/reducers/accommodation/createAccommodationReducer.test.js
  src/__tests__/sidebar.js
  src/__tests__/views/accommodation/createAccommodationView.test.js
  src/assets/css/accommodation.scss
  src/assets/css/base.scss
  src/assets/css/footer.scss
  src/assets/css/modal.scss
  src/components/InputField.js
  src/components/Sidebar/SideDrawer/SideDrawer.js
  src/components/header.js
  src/components/modal.js
  src/constants/accommodation.js
  src/containers/accommodation/createAccommodation.js
  src/containers/user/email/successfulVerification.js
  src/containers/user/email/verifyEmail.js
  src/containers/user/password/forgotPassword.js
  src/containers/user/password/resetPassword.js
  src/helpers/cloudinaryWidget.js
  src/helpers/isTravelAdmin.js
  src/redux/actionTypes/accommodationActionTypes.js
  src/redux/actions/createAccommodationActions.js
  src/redux/reducers/accommodation/createAccommodationReducer.js
  src/redux/reducers/accommodation/index.js
  src/redux/reducers/index.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/Dashboard/sidebar/RightSide.js
  src/views/Dashboard/sidebar/TopRightSide.js
  src/views/accommodation/createAccommodationView.js
Labels: feedback implemented

#18 #170569791 all private route should be protected
  .vscode/settings.json
  html-report/report.html
  package-lock.json
  src/App.js
  src/__mocks__/__loginTestMock__/loginMock.js
  src/__mocks__/auth/authMock.js
  src/__mocks__/fileMock.js
  src/__tests__/actions/auth/signin.test.js
  src/__tests__/actions/auth/signup.test.js
  src/__tests__/containers/successfulVerification.test.js
  src/__tests__/containers/verifyEmail.test.js
  src/__tests__/reducers/auth/signin.test.js
  src/__tests__/reducers/auth/signup.test.js
  src/__tests__/sidebar.js
  src/__tests__/verifyToken.js
  src/__tests__/views/auth/loginView.test.js
  src/components/Profile.js
  src/containers/Trips/Requests.js
  src/containers/Trips/SingleRequest.js
  src/containers/user/email/successfulVerification.js
  src/containers/user/email/verifyEmail.js
  src/containers/user/signin/signin.js
  src/containers/user/signup/signup.js
  src/helpers/findWordInText.js
  src/helpers/tokenExist.js
  src/helpers/verifyToken.js
  src/redux/actions/authActions.js
  src/redux/actions/signinActions.js
  src/redux/reducers/authReducers/signinReducer.js
  src/redux/reducers/authReducers/signupReducers.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/index.js
Labels: done, implementing feedback

#31 #169258586 Avail requests for approval to managers
  src/App.js
  src/__mocks__/fileMock.js
  src/__mocks__/trips/requests.js
  src/__tests__/actionTests/approveRequestActionTest.js
  src/__tests__/actionTests/availRequestsActionTests.js
  src/__tests__/componentTests/roundTripTests.js
  src/__tests__/containers/ApprovalTable.test.js
  src/__tests__/containers/__snapshots__/ApprovalTable.test.js.snap
  src/__tests__/reducerTests/approveRequestReducerTest.js
  src/__tests__/reducerTests/availRequestsReducerTests.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/__tests__/views/trips/MangerViewTest.js
  src/__tests__/views/trips/__snapshots__/CommonSingleRequest.test.js.snap
  src/__tests__/views/trips/__snapshots__/MangerViewTest.js.snap
  src/assets/css/Home.css
  src/assets/css/table.scss
  src/assets/images/background-home.jpg
  src/assets/images/background-home2.jpg
  src/assets/images/photo-1512100356356-de1b84283e18.jpeg
  src/constants/trips.js
  src/containers/Trips/ApprovalTable.js
  src/containers/TripsContainer/SingleRequest.js
  src/redux/actionTypes/authActionTypes.js
  src/redux/actionTypes/tripsActionTypes.js
  src/redux/actions/tripsActions/approveRequestAction.js
  src/redux/actions/tripsActions/availRequestsActions.js
  src/redux/reducers/tripReducers/approveRequestsReducers.js
  src/redux/reducers/tripReducers/availRequestsReducers.js
  src/redux/reducers/tripReducers/index.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/CommonTable.js
  src/views/trips/ManagerView.js
  src/views/trips/RequestsView.js
  src/views/trips/SingleRequestView.js
Labels: done, ready for review

#34 #170663818 Users should be able to create multicity trip requests
  src/App.js
  src/__mocks__/trips/multicity.js
  src/__tests__/actions/Trips/multicity.js
  src/__tests__/containers/Trips/multicity.js
  src/__tests__/reducers/Trips/multicity.js
  src/assets/css/multicity.scss
  src/components/trips/DateFields.js
  src/containers/Trips/MulticityTrip.js
  src/helpers/convertField.js
  src/redux/actionTypes/multicityActionType.js
  src/redux/actions/multicityActions.js
  src/redux/reducers/index.js
  src/redux/reducers/multicityReducer.js
  src/views/trips/Multicity.js
Labels: done, ready for review

#29 #1692585870 a user or a manager should be able to comment on a trip requests
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__tests__/actions/Trips/fetchRequests.test.js
  src/__tests__/componentTests/roundTripTests.js
  src/__tests__/reducers/Trips/fetchRequest.test.js
  src/__tests__/reducers/Trips/signup.test.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/__tests__/views/trips/CommonTable.test.js
  src/assets/css/sidenav/sidebar.scss
  src/assets/css/table.scss
  src/components/PopUp.js
  src/containers/Trips/ApprovalTable.js
  src/containers/TripsContainer/Requests.js
  src/containers/TripsContainer/RoundTrip.js
  src/containers/TripsContainer/SingleRequest.js
  src/helpers/errorProcessor.js
  src/redux/actionTypes/tripActionTypes.js
  src/redux/actions/authActions.js
  src/redux/actions/tripsActions/fetchRequests.js
  src/redux/reducers/tripReducers/requestsReducers.js
  src/redux/store/initialState.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/CommonTable.js
  src/views/trips/RequestsView.js
  src/views/trips/SingleRequestView.js
Labels: done, ready for review

#33 #169258608 User get all trips made between specific dates
  html-report/report.html
  jest.config.js
  src/App.js
  src/__tests__/actions/Trips/getStatsAction.test.js
  src/__tests__/reducers/Trips/getTripStats.test.js
  src/assets/css/statsTrip.scss
  src/assets/css/table.scss
  src/components/GetStatsNav.js
  src/constants/trips.js
  src/containers/TripsContainer/SingleRequest.js
  src/containers/trips/SearchStats.js
  src/redux/actionTypes/getStatsActionTypes.js
  src/redux/actions/tripsActions/statsTripActions.js
  src/redux/reducers/tripReducers/getStatsTripReducers.js
  src/redux/reducers/tripReducers/index.js
  src/redux/store/initialState.js
  src/views/trips/SearchTripStats.js
Labels: ready for review

#32 #169258584 Super admin should be able to assign roles
  html-report/report.html
  jest.config.js
  src/App.js
  src/__mocks__/admin/admin.js
  src/__tests__/actions/admin/adminAction.test.js
  src/__tests__/components/SelectOption.test.js
  src/__tests__/components/__snapshots__/SelectOption.test.js.snap
  src/__tests__/containers/admin/UserRoles.test.js
  src/__tests__/helpers/checkPrevilege.test.js
  src/__tests__/helpers/isTravelAdmin.test.js
  src/__tests__/reducerTests/profileReducerTests.js
  src/__tests__/reducers/admin/adminReducer.js
  src/__tests__/views/admin/assignRoleView.js
  src/assets/css/App.scss
  src/assets/css/selectOption.scss
  src/assets/css/table.scss
  src/assets/images/addNewTrip.png
  src/assets/images/statistics.png
  src/assets/images/users.png
  src/components/SelectOption.js
  src/components/Sidebar/SideDrawer/SideDrawer.js
  src/constants/admin.js
  src/containers/Trips/ApprovalTable.js
  src/containers/TripsContainer/SingleRequest.js
  src/containers/admin/UserRoles.js
  src/containers/admin/allUsers.js
  src/containers/user/signin/signin.js
  src/helpers/checkPrevilege.js
  src/helpers/filter.js
  src/redux/actionTypes/adminActionTypes.js
  src/redux/actionTypes/profileActionTypes.js
  src/redux/actions/admin/adminAction.js
  src/redux/actions/getAllUsersActions.js
  src/redux/reducers/admin/adminReducer.js
  src/redux/reducers/getAllUsersReducers.js
  src/redux/reducers/index.js
  src/redux/store/initialState.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/admin/UserRolesView.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
Labels: done, feedback implemented

#35 #170918418 Implement feedback
  html-report/report.html
  src/__mocks__/trips/requests.js
  src/__tests__/actions/paginationAction.test.js
  src/__tests__/containers/admin/UserRoles.test.js
  src/__tests__/helpers/pagination.test.js
  src/__tests__/reducers/PaginationReducer.test.js
  src/__tests__/sidebar.js
  src/__tests__/views/trips/CommonTable.test.js
  src/__tests__/views/trips/MangerViewTest.js
  src/__tests__/views/trips/Requests.test.js
  src/__tests__/views/trips/RequestsView.test.js
  src/assets/css/accommodation.scss
  src/assets/css/authentication.scss
  src/assets/css/base.scss
  src/assets/css/multicity.scss
  src/assets/css/oneway.scss
  src/assets/css/roundtrip.scss
  src/assets/css/table.scss
  src/assets/images/trash.png
  src/components/GetStatsNav.js
  src/components/PopUp.js
  src/constants/trips.js
  src/containers/Trips/ApprovalTable.js
  src/containers/TripsContainer/Requests.js
  src/containers/admin/UserRoles.js
  src/containers/admin/allUsers.js
  src/helpers/Paginate.js
  src/redux/actionTypes/PaginationActionTypes.js
  src/redux/actions/PaginationAction.js
  src/redux/actions/tripsActions/fetchRequests.js
  src/redux/reducers/PaginationReducer.js
  src/redux/reducers/index.js
  src/redux/store/initialState.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/ManagerView.js
  src/views/trips/RequestsView.js
  src/views/trips/SearchTripStats.js
Labels: ready for review

#37 #170893840 Design dashboard home page
  html-report/report.html
  src/__mocks__/fileMock.js
  src/__tests__/actionTests/getAllBookingActionTests.js
  src/__tests__/actionTests/getMostTravelledActionTests.js
  src/__tests__/reducerTests/getAllBookingsReducerTests.js
  src/__tests__/reducerTests/getMostTravelledReducerTests.js
  src/__tests__/views/Dashboard.test.js
  src/__tests__/views/__snapshots__/Dashboard.test.js.snap
  src/assets/css/homeDashboard.css
  src/assets/images/accommodation_icon/travel.jpg
  src/assets/images/accommodation_icon/travel1.png
  src/assets/images/home-dashboard_icon/icons8-city-24.png
  src/assets/images/home-dashboard_icon/icons8-hotel-bed-30.png
  src/assets/images/home-dashboard_icon/icons8-map-marker-24.png
  src/redux/actionTypes/accommodationActionTypes.js
  src/redux/actionTypes/bookingActionTypes.js
  src/redux/actions/bookings/getAllBookingsActions.js
  src/redux/actions/getMostTravelledAccommodationAction.js
  src/redux/reducers/accommodation/getMostTravelledReducer.js
  src/redux/reducers/accommodation/index.js
  src/redux/reducers/bookings/getAllBookingReducers.js
  src/redux/reducers/bookings/index.js
  src/redux/reducers/index.js
  src/views/Dashboard.js
Labels: ready for review

#36 #170889022 Users should be able to view all accommodations
  html-report/report.html
  package-lock.json
  package.json
  src/App.js
  src/__mocks__/accommodation/viewAccommodation.js
  src/__tests__/ImproveTest.js
  src/__tests__/__snapshots__/ImproveTest.js.snap
  src/__tests__/actions/accommodation/viewAccommodations.js
  src/__tests__/containers/accommodation/__snapshots__/viewAccommodation.test.js.snap
  src/__tests__/containers/accommodation/viewAccommodation.test.js
  src/__tests__/helpers/findTotalAverages.js
  src/__tests__/reducers/accommodation/viewAccommodation.js
  src/assets/css/accommodation.scss
  src/assets/css/accommodation/allAccommodation.scss
  src/assets/css/multicity.scss
  src/assets/css/roundtrip.scss
  src/assets/css/sidenav/sidebar.scss
  src/assets/images/accommodation_icon/view_accommodation_24.png
  src/assets/images/dislike_icon/thumbs-down_128.png
  src/assets/images/dislike_icon/thumbs-down_16.png
  src/assets/images/dislike_icon/thumbs-down_24.png
  src/assets/images/dislike_icon/thumbs-down_32.png
  src/assets/images/dislike_icon/thumbs-down_64.png
  src/assets/images/like_icon/thumbs-up_128.png
  src/assets/images/like_icon/thumbs-up_16.png
  src/assets/images/like_icon/thumbs-up_24.png
  src/assets/images/like_icon/thumbs-up_32.png
  src/assets/images/like_icon/thumbs-up_64.png
  src/assets/images/room_bed/room-bed_16.png
  src/assets/images/room_bed/room-bed_24.png
  src/assets/images/room_bed/room-bed_32.png
  src/assets/images/room_bed/room-bed_64.png
  src/assets/images/room_map/map_16.png
  src/assets/images/room_map/map_24.png
  src/assets/images/room_map/map_32.png
  src/assets/images/room_map/map_64.png
  src/assets/images/star_rate/star-rate_128.png
  src/assets/images/star_rate/star-rate_16.png
  src/assets/images/star_rate/star-rate_24.png
  src/assets/images/star_rate/star-rate_32.png
  src/assets/images/star_rate/star-rate_64.png
  src/components/GetStatsNav.js
  src/components/Sidebar/SideDrawer/SideDrawer.js
  src/containers/accommodation/ViewAccommodations.js
  src/containers/trips/SearchStats.js
  src/helpers/averageRatings.js
  src/helpers/joinLikesAccomodation.js
  src/redux/actionTypes/accommodationActionTypes.js
  src/redux/actions/PaginateAction.js
  src/redux/actions/allAccommodation.js
  src/redux/reducers/accommodation/viewAccomodationReducer.js
  src/redux/reducers/index.js
  src/views/Dashboard/sidebar/LeftSide.js
  src/views/accommodation/ViewAccomodation.js
  src/views/trips/SearchTripStats.js
Labels: ready for review

#38 #169258591 User search functionality
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/admin/admin.js
  src/__mocks__/search/search.js
  src/__mocks__/trips/requests.js
  src/__tests__/actions/search/searchAction.test.js
  src/__tests__/containers/admin/UserRoles.test.js
  src/__tests__/containers/admin/__snapshots__/UserRoles.test.js.snap
  src/__tests__/helpers/filter.test.js
  src/__tests__/reducers/search/searchReducer.test.js
  src/__tests__/views/trips/CommonTable.test.js
  src/__tests__/views/trips/RequestsView.test.js
  src/assets/css/homeDashboard.css
  src/assets/css/oneway.scss
  src/assets/css/roundtrip.scss
  src/assets/css/sidenav/sidebar.scss
  src/assets/css/table.scss
  src/components/GetStatsNav.js
  src/components/PopUp.js
  src/constants/admin.js
  src/constants/trips.js
  src/containers/TripsContainer/Requests.js
  src/containers/TripsContainer/SingleRequest.js
  src/containers/accommodation/ViewAccommodations.js
  src/containers/admin/UserRoles.js
  src/containers/admin/allUsers.js
  src/helpers/filter.js
  src/redux/actionTypes/searchActionTypes.js
  src/redux/actions/allAccommodation.js
  src/redux/actions/search/searchAction.js
  src/redux/reducers/index.js
  src/redux/reducers/searchReducers/searchReducers.js
  src/redux/store/initialState.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/CommonTable.js
  src/views/trips/ManagerView.js
  src/views/trips/RequestsView.js
Labels: ready for review

#39 #69258595 A user should be able to edit travel requests
  package-lock.json
  package.json
  src/__mocks__/improveTestMockup.js
  src/__mocks__/trips/requests.js
  src/__tests__/__snapshots__/improveTests.js.snap
  src/__tests__/actions/popUp.test.js
  src/__tests__/improveTests.js
  src/__tests__/reducers/popUp.test.js
  src/__tests__/views/trips/CommonRequests.test.js
  src/__tests__/views/trips/CommonSingleRequest.test.js
  src/__tests__/views/trips/CommonTable.test.js
  src/__tests__/views/trips/DeleteComment.test.js
  src/__tests__/views/trips/EditTrip.test.js
  src/__tests__/views/trips/Requests.test.js
  src/__tests__/views/trips/SingleRequests.test.js
  src/__tests__/views/trips/__snapshots__/CommonRequests.test.js.snap
  src/__tests__/views/trips/__snapshots__/DeleteComment.test.js.snap
  src/__tests__/views/trips/__snapshots__/EditTrip.test.js.snap
  src/assets/css/table.scss
  src/components/PopUp.js
  src/constants/trips.js
  src/containers/TripsContainer/SingleRequest.js
  src/helpers/matchCitiesWithIds.js
  src/redux/actionTypes/popUpActionType.js
  src/redux/actions/popUpAction.js
  src/redux/actions/tripsActions/fetchRequests.js
  src/redux/reducers/index.js
  src/redux/reducers/multicityReducer.js
  src/redux/reducers/popUpReducer.js
  src/redux/store/initialState.js
  src/views/trips/CommonRequests.js
  src/views/trips/CommonSingleRequest.js
  src/views/trips/CommonTable.js
  src/views/trips/DeleteComment.js
  src/views/trips/EditTrip.js
  src/views/trips/SingleRequestView.js
Labels: ready for review
